### ISSUE TITLE
module 'pylablib.core.devio.backend' has no attribute 'FT232DeviceBackend'

### ISSUE THREAD

**Issue by Yrisch** [AlexShkarin/pyLabLib-v0#6]
Hello,

I'm trying to interface thorlabs motors with your lib but can't initialize them. During the init this error popped out:
conn=backend.FT232DeviceBackend.combine_conn(conn,(None,115200))
AttributeError: module 'pylablib.core.devio.backend' has no attribute 'FT232DeviceBackend'
This is strange, everything seems to be ok in the install. 
I tried to change OS and python version but nothing worked (currently running on python 3.8).

Thanks,
Yann

**Comment by AlexShkarin** [comment]
Dear Yann,

It looks like your missing pyft232 package. You can install it from pip as `pip install pyft232`. Unfortunately, this post is not currently very well documented. I'm sorry for the confusion.

Let me know if that resolves the issue,

Alexey.

**Comment by Yrisch** [comment]
I tried this too without result. Install an uninstall pyft232. I'll continue to search on my own. 
If you have an idea let it me know.

Thanks for your fast answer. 

Yann.

**Comment by AlexShkarin** [comment]
Hmm, that's strange.

Can you import pyft232? If you type `import ft232` in the Python console, does it work?

Can you also tell me the version that you're using? It works for me with 0.9.

**Comment by Yrisch** [comment]
You hit something ! my ft232 package doesn't want to import ! I tried to use v0.9, still without result. Maybe I missed something in my install ? 
 It seems he can't read a .so lib. Maybe an OS restriction. I'll try to fix that and keep you informed.

Thanks, 

Yann.

**Comment by AlexShkarin** [comment]
Ah, I see. Thank you for letting me know!

Are you using Linux? To be honest, I haven't extensively tried the library there, and I'm not even sure if pyft232 works on Linux. I'll try to do more extensive testing in that direction for the next version of the package.

Alexey.

**Comment by Yrisch** [comment]
Good news ! I fixed my ft232 package and it can be import now. That fixed my first bug. The issue was that the lib wasn't looking in the right dir for the .so. I have a new bug but it's moving forward !!

thanks a lot for the hint !

Yann

**Comment by Yrisch** [comment]
Ok, I think it's completely fixed ! 

Thanks a lot for your help !

Yann

**Comment by aromanillos** [comment]
Hello, I am having a similar issue so maybe your solution could be similar. I am using Python 3.6 in Windows 10, in a conda env to be more precise. I am using it for some Thorlabs KDC motors ( it worked in the past, but i am building a new setup)

First I got the same error 
**AttributeError: module 'pylablib.core.devio.backend' has no attribute 'FT232DeviceBackend'**


then i checked for pyft232 and i got the following error 



**import ft232
Traceback (most recent call last):

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\site-packages\ft232\__init__.py", line 19, in <module>
    from .d2xx import list_devices

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\site-packages\ft232\d2xx.py", line 29, in <module>
    d2xx = c.windll.ftd2xx

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\ctypes\__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-768fc14765c7>", line 1, in <module>
    import ft232

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\site-packages\ft232\__init__.py", line 24, in <module>
    from .libftdi import list_devices

  File "C:\Users\User-Setup8\anaconda3\envs\testlabauto\lib\site-packages\ft232\libftdi.py", line 36, in <module>
    ftdi.ftdi_new.restype = c.c_void_p

NameError: name 'ftdi' is not defined**

something that could look familiar to any previous issue? or any idea what could happen?

**Comment by Yrisch** [comment]
Hi,

It seems to be a driver issue. Have you install ftdi driver for Windows ?

**Comment by aromanillos** [comment]
Normally this drivers should come when i install the Kinetic software for the device i am using, or at least i did like that on the past... i will keep looking 

thanks for your help

**Comment by AlexShkarin** [comment]
Looks like I have the same problem. I suspect, one of the more recent Windows updates might be to blame, sometimes they remove DLLs from the ``System32`` folder.

I managed to fix it by copying ``C:\Program Files\Thorlabs\APT\Drivers\APT\USB Driver\amd64\ftd2xx64.dll`` to ``C:\Windows\System32`` and renaming it to ``ftd2xx.dll``. Perhaps, reinstalling APT would also help, I'll check it and report later.

**Comment by AlexShkarin** [comment]
No, reinstalling APT does not seem to work in my case.

On the other hand, you can install FTDI drivers directly from the website (https://ftdichip.com/drivers/d2xx-drivers/ with the excutable installer for the most recent version at https://www.ftdichip.com/Drivers/CDM/CDM212362_Setup.zip). It also copies the DLL to the ``System32`` folder.

**Comment by aromanillos** [comment]
indeed, this solves the issue for me, at least for the time being.

Thank you for the support, even it was not purely related with the library!

**Comment by AlexShkarin** [comment]
No problem! Thanks for letting me know that it worked!
I'll make sure to rescribe this issue in the documentation for the next version.

**Comment by pepegacross** [comment]
Hello,

I am having the exact same problem, getting this error: AttributeError: module 'pylablib.core.devio.comm_backend' has no attribute 'FT232DeviceBackend'

I have installed the ftdi drivers and the correct .dll file is in my System32 folder.  Alternatively, if I 'import ft232' I get the following error: 

Traceback (most recent call last):

  File ~\.spyder-py3\untitled0.py:2 in <module>
    import ft232

  File ~\anaconda3\lib\site-packages\ft232\__init__.py:24 in <module>
    from .libftdi import list_devices

  File ~\anaconda3\lib\site-packages\ft232\libftdi.py:36 in <module>
    ftdi.ftdi_new.restype = c.c_void_p

NameError: name 'ftdi' is not defined

Any help would be really appreciated! Thanks!

**Comment by AlexShkarin** [comment]
It does look like there are problems with pyft232 not finding the right dll. Can you make sure that ``ftd2xx.dll`` is indeed in your ``Systems32`` folder?

To narrow down the issue, you can also try running
```python
import ctypes
lib=ctypes.windll.ftd2xx
v=ctypes.c_ulong()
lib.FT_CreateDeviceInfoList(ctypes.byref(v))
print(v.value)
```
Ideally, it should report the number of available ftdi devices. But if it raises an error, it could point to a specific problem.

**Comment by pepegacross** [comment]
Hi Alex,

Thanks for the response.    I double (more like quadruple) checked my System 32 and ftd2xx.dll is indeed there, and named correctly.  Running the code snippet you posted yields:

Traceback (most recent call last):

  File ~\.spyder-py3\untitled0.py:2 in <module>
    lib=ctypes.windll.ftd2xx

  File ~\anaconda3\lib\ctypes\__init__.py:452 in __getattr__
    dll = self._dlltype(name)

  File ~\anaconda3\lib\ctypes\__init__.py:382 in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application

I am running the code on Spyder IDE through Anaconda - unsure if that could be part of the problem?  Really appreciate the help!

**Comment by AlexShkarin** [comment]
It looks like the DLL is there, but the OS can not load it. You're running 64-bit Windows and Python, right? To make sure, try running
```python
import platform
print(platform.architecture()[0])
```
and check that it prints ``64bit``. If that's the case, then you can try loading the DLL directly from the Tholabs APT folder by running (preferably in a freshly started console)
```python
import os
os.chdir(r'C:\Program Files\Thorlabs\APT\Drivers\APT\USB Driver\amd64')
import ctypes
lib=ctypes.windll.LoadLibrary("ftd2xx64.dll")
v=ctypes.c_ulong()
lib.FT_CreateDeviceInfoList(ctypes.byref(v))
print(v.value)
```
This assumes that Thorlabs APT is installed in its default folder.

If even that does not work, and you are sure you are running 64-bit Python, then the only fix I can think of right now is to try and reinstall Thorlabs APT software, or to download and install FTDI chip drivers directly from the manufacturer at https://www.ftdichip.com/Drivers/CDM/CDM212362_Setup.zip

**Comment by pepegacross** [comment]
Running the first snippet of code correctly yielded `64bit`.   The second code gives '0'.  Re-installing APT then re-copying the .dll to System 32 seemed to fix it, though; the only issue being that when I run 'from pylablib.devices import Thorlabs
Thorlabs.list_kinesis_devices()' to try and get a list of the connected motors to my machine it just yields nothing, and if I do 'print(Thorlabs.list_kinesis_devices())' I just get an empty array so evidently something isn't getting recognized correctly.  Thanks for your help!
